# Version will be manually specified through RLSApi\RLSApi.csproj instead of CI versioning.

branches:
  only:
  - master

assembly_info:
  patch: false

configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - appveyor-retry dotnet restore "src\RLSApi" -v Minimal

build_script:
  - dotnet restore
  - dotnet build "src\RLSApi" -c Release --version-suffix %LABEL%
  
after_build:
  - dotnet pack "src\RLSApi" -c Release --version-suffix %LABEL%
  
artifacts:
  - path: .\**\artifacts\*.nupkg

cache:
  - '%USERPROFILE%\.nuget\packages'